### ISSUE TITLE
開催するためのタスク

### ISSUE THREAD

**Issue by takkanm** [asakusarb/oedo08#17]
開催まで 1 ヶ月弱なので、残タスクを洗い出しておきたい。

- [x] Speaker を決める
  - [x] 基調講演 & 友人トーク以外の人数を決める
  - [x] Speaker にお願いをする
- [x] 出し物の有無を決める
- [x] タイムテーブルを決める
- [x] Doorkeeper に募集ページをつくる
  - [x] 料金を決定する
- [x] 名札を作る
  - [x] デザイン発注
  - [x] キンコーズ発注
    - 今年は当日にとりにいかないようにしたい
  - [x] 名札ケース用意
- [x] 当日いるもの用意
  - [x] 名札用ペン
  - [x] イーゼルパッド 
  - [x] 賽銭箱
- [x] 懇親会の会場を決める
  - jorker1007 さんが決めてた？
- [x] 懇親会用 Dorkeeper を作って公開する

**Comment by taea** [comment]
🤔 After Party 会場手配や募集ページとかも必要？

**Comment by hsbt** [comment]
名札のペン、賽銭箱は @hsbt が保有してます

**Comment by amatsuda** [comment]
チケット販売開始しました！ https://asakusarb.doorkeeper.jp/events/102613

@taea ところで、すっかり忘れてたんですけど、Doorkeeperのイベントページ用にゴロゴロした感じの画像があったら映える感じでうれしいです。
必須ではないのでお手すきの際で構わないんですが、なんかいい感じのやつをご用意いただけませんでしょうか？サイズは 900 x 300 が推奨とのことです。

**Comment by taea** [comment]
@amatsuda 

画像、了解です〜
午前中外出しておりまして、午後以降に対応します

**Comment by taea** [comment]
@amatsuda

おまたせしました！ Doorkeeper 用画像作りました！
![oedo08-doorkeeper](https://user-images.githubusercontent.com/341101/72135240-596d4d80-33c9-11ea-9600-c08a78569a7e.png)

サイトにDoorkeeper へのリンクボタンも、後ほど追加してプルリク送ります〜

**Comment by amatsuda** [comment]
DKに貼らせていただきました！ありがとうございます！！

**Comment by emorima** [comment]
懇親会について昨日(1/21)のAsakusa.rbで松田さんと話して、以下のようにしています。
- 5656会館の下
  - やめておこう
- 以前 Asakusa.rb新年会でも行ったことのあるQue bom! に連絡
  - 予約が2組(or 2人) いるとのことで、お店から予約の方にご連絡して、予約の方に変更可能か確認の上、江森宛に連絡もらえることになっています (今週くらいを目安)

**Comment by emorima** [comment]
懇親会について追記
- Que bom! 
  - 予約の調整をしてもらっている状況(とても頑張ってもらっている印象)
  - 1/30(木) 夜に再度連絡して、ダメなら諦めるとしてある

- とんぼ
  - 仮押さえ(80名)済
  - メニュー等は別途連絡すると伝えてある

**Comment by emorima** [comment]
### とんぼの場合

  - 18:30~
  - 送迎が可能かを聞く
  - 5,500円 の季節の会席(飲み放題なし)

**Comment by hsbt** [comment]
懇親会手配ありがとうございます!

**Comment by emorima** [comment]
懇親会について Que bom! がお客様と連絡できて貸切できました！
(とんぼの仮押さえもキャンセル済み)

- 18:30〜お食事開始
- 飲み放題付き 5,500円(税抜)/人
  - 80名と伝えてある
  - 65名は保証して欲しいとのこと
- プロジェクター利用可
  - 前日までに利用するかを連絡する

DKの権限頂ければ、イベントの下書きまで作ります！ @amatsuda @hsbt

**Comment by hsbt** [comment]
うおー、シュラスコ食べたかったので楽しみ。

doorkeeper 登録のメールに管理者招待のメールを出しましたー時期が時期だけに、手洗いはしっかりって感じかなあ。あと風邪気味の人はご自愛してね!も。

**Comment by emorima** [comment]
DKでイベントの下書き作りましたので、確認お願いします！

- 税込 6,050円/人 となると思うので、6,000円/人 としてあります
- スピーカーは購入不要としてあります
  - 人数わからなくなるから、スピーカー枠も必要でしょうか？
- 時間は18:30~20:30になります
  - お店から21:00撤収と言われています

**Comment by amatsuda** [comment]
ありがとうございます。
おそらく本編でちょっと利益が出るので、懇親会のお値段は、4000円か5000円か5656円ぐらいで良いかと思います。

**Comment by hsbt** [comment]
先にスピーカーと中の人( @amatsuda @hsbt @emorima あとは誰かな)の人は入れておくのがいいと思います!

**Comment by emorima** [comment]
以下、２種類作りました！
- 5656 Ticket, 5656 JPY (56人)
- Cheaper Ticket for Those Who Don't Want to Pay 5656 Yen, 4000JPY (24人)

**Comment by hsbt** [comment]
スピーカー、今のうちにいれておきますー

**Comment by hsbt** [comment]
入れました。ただ 5 名ほどわからなかったので後で入れます。

スピーカーと1-2名のバッファで 24 人は枠を確保して残りを懇親会の 5656 チケットって感じにちょっといじりましたー。 @emorima さんが作ってくれた安い方のチケットが無くなってしまう感じなんですが、スピーカーが安い方、って見えるのも何なので全部 5656 にしちゃいました。

**Comment by hsbt** [comment]
イーゼルパッド僕かって持っていくかな

**Comment by amatsuda** [comment]
> 以下、２種類作りました！
> 
> 5656 Ticket, 5656 JPY (56人)
> Cheaper Ticket for Those Who Don't Want to Pay 5656 Yen, 4000JPY (24人)

えー、なんかこういうの感じ悪くないすか？なんかもう、全員4000円でいいんじゃないすか。

**Comment by hsbt** [comment]
今は 5656 1つのみですね

**Comment by hsbt** [comment]
現金化したら1割 stripe に持っていかれるのでそれを見通しての金額にするのがいいかなあ

**Comment by a-wakou** [comment]
朝はだいたい７時半ぐらいには浅草周辺に居るので、当日朝については、対応可能です。

プロジェクタやマイクの試しと受付準備と受付対応とかでしょうかね。

受付に必要な物、朝あった方が良いものなど対応させて頂きます。

名簿は Doorkeeper から印刷？

anonmousの方の確認は管理者から情報頂く必要ありそうですが、当日朝に会社で印刷してから会場に行くとかもできるかと思います。

**Comment by takkanm** [comment]
@a-wakou 当日の朝は、昨年だと以下のような感じだったと思います。

- 会場の人にマイク、スクリーン等の準備を依頼
  - 今年はプロジェクターも会場の備え付けなので、その準備もお願いすることになりそう
- 名札を書いてもらうための準備
  -  名札、名札ケース、ペン等の準備
- イーゼルパッドを使っての会場ファシリテーション
  - 受け付けどこかぐらいだったと思います。

例年参加者の受け付けについては、参加者の方がちゃんと登録してきてくれていることを信じ、ほとんどしてないません。なので、会場で困ってそうな人に声かけて名札書いてもらっているくらです。

**Comment by hsbt** [comment]
イーゼルパッド買ったので持っていきます。柴田が持っていくものリスト

 * HDMI 変換アダプタ(Tyep-C, mini-DP)
 * イーゼルパッド
 * 名札
 * 名札ケース
 * 賽銭箱
 * マッキー
 * AC アダプタ適当にいくつか

**Comment by a-wakou** [comment]
当日朝情報ありがとうございます！
会場がわかれば、あとは声が聞こえて、資料が見えれば、という感じですか。
松田さんからも、少人数で負担少なく運用しているという話もありました。
参加者含めた皆で協力しあう感じでの継続よい感じですね。

**Comment by hsbt** [comment]
@a-wakou 午前 9:00 くらいに集まろうかねえという話をしていたので、何かしら設営をお手伝いいただけるのならその時間にお願いします!

**Comment by emorima** [comment]
懇親会ですが、未登録だった くノ一 トーク(がーるず(仮))の登壇者を登録しときました。
現時点で 67名です。
お店のプロジェクターは使用しますか？

お店のプロジェクターを使用する場合、前日に連絡することになっているので、
その時に人数も連絡しようと思います。

**Comment by a-wakou** [comment]
ありがとうございます。
９時くらい了解です。

**Comment by hsbt** [comment]
@emorima プロジェクタは使います! 人数は現時点で 71 ですが、昼にまだ席ありますよというのを出そうと思うので、夕方以降の連絡で大丈夫でしょうか?

**Comment by emorima** [comment]
@hsbt  プロジェクタ使うってことで了解です！電話は20時頃にしようと思っています！

**Comment by emorima** [comment]
お店に人数の連絡ついでに、PCに繋いでプロジェクター使いたい旨伝えておきました！

**Comment by hsbt** [comment]
開催終わっていました!
