### ISSUE TITLE
プロジェクタの情報のお知らせ

### ISSUE THREAD

**Issue by hsbt** [asakusarb/oedo08#39]
登壇者の皆さん向けです ( `@here` があるといいなあ )

```
機種　
ソニーコーポレーション
型番
VPL-FHZ66/WC3SYQ
レンズ
VPLL-Z3032
```

**Comment by hsbt** [comment]
https://www.sony.jp/vpl/products/VPL-FHZ66/ これかな

**Comment by hsbt** [comment]
Type-C HDMI アダプタ(anker のやつ)は持っていきます。

**Comment by amatsuda** [comment]
🙏

**Comment by amatsuda** [comment]
＠here じゃないけど、`oedo08` teamでも作っときますかねぇ(この先使うことがあるのかどうか疑問ですが…)

**Comment by hsbt** [comment]
なぜか miniDP-HDMI アダプタも手元にあったので持っていきます!

**Comment by amatsuda** [comment]
> ＠here じゃないけど、oedo08 teamでも作っときますかねぇ(この先使うことがあるのかどうか疑問ですが…)

つくった。
ということで、こちらのスレが大江戸Ruby会議08のプロジェクター情報になります。 > @asakusarb/oedo08 のみなさん

**Comment by okuramasafumi** [comment]
アスペクト比は`16:10`みたいですね。スライドは`16:9`で作るとよいのでしょうか。

**Comment by hsbt** [comment]
開催終わっていたのでクローズします。お疲れ様でした。
